# Generated by Django 5.1.2 on 2024-10-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_event', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('description_courte', models.TextField()),
                ('lien_page_event', models.URLField(blank=True, null=True)),
                ('image_event', models.ImageField(upload_to='imgevent/')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo_profile', models.ImageField(upload_to='photos/')),
                ('tag_discord', models.CharField(max_length=100, unique=True)),
                ('lien_github', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(max_length=100)),
                ('bureau', models.BooleanField(default=False)),
                ('com', models.BooleanField(default=False)),
                ('cyber', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('termine', 'Terminé'), ('en_cours', 'En Cours'), ('a_venir', 'À Venir')], max_length=50)),
                ('lien_gitlab', models.URLField(blank=True, null=True)),
                ('image_projet', models.ImageField(upload_to='imgproj/')),
                ('developpeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.membre')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.role'),
        ),
    ]
