# Generated by Django 5.1.2 on 2024-10-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='photo_profile',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
