# Generated by Django 5.1.2 on 2024-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_membre_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_event',
            field=models.ImageField(upload_to='media/imgevent/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='image_projet',
            field=models.ImageField(upload_to='media/imgproj/'),
        ),
    ]
