# Generated by Django 5.1.2 on 2024-10-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_events_image_event_alter_projets_image_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_event',
            field=models.ImageField(upload_to='static/media/imgevent/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='photo_profile',
            field=models.ImageField(upload_to='static/media/photos/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='image_projet',
            field=models.ImageField(upload_to='static/media/imgproj/'),
        ),
    ]
