# Generated by Django 5.1.2 on 2024-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_events_image_event_alter_membre_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='static/media/photos/'),
        ),
    ]
