# Generated by Django 5.1.2 on 2024-10-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_membre_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_event',
            field=models.ImageField(upload_to='imgevent/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='image_projet',
            field=models.ImageField(upload_to='imgproj/'),
        ),
    ]
