# Generated by Django 5.1.2 on 2024-10-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_events_image_event_alter_membre_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
