# Generated by Django 5.1.2 on 2024-10-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_membre_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.role'),
        ),
    ]
