# Generated by Django 5.1.2 on 2024-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_membre_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='lien_lk',
            field=models.URLField(blank=True, null=True),
        ),
    ]
