# Generated by Django 5.1.2 on 2024-10-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_membre_lien_lk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Projets',
            new_name='Projet',
        ),
    ]
