# Generated by Django 5.1.2 on 2024-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_events_event_rename_projets_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image_projet',
            field=models.ImageField(blank=True, null=True, upload_to='imgproj/'),
        ),
    ]
