# Generated by Django 5.1.2 on 2024-10-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_projet_image_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='developpeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.membre'),
        ),
    ]
