# Generated by Django 5.1.2 on 2024-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('lien_doc', models.URLField(blank=True, null=True)),
                ('image_doc', models.ImageField(upload_to='imgdoc/')),
            ],
        ),
    ]
