# Generated by Django 5.1.2 on 2024-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='developpeur',
        ),
        migrations.AddField(
            model_name='projet',
            name='techno',
            field=models.ManyToManyField(blank=True, to='webapp.techno'),
        ),
        migrations.AddField(
            model_name='projet',
            name='developpeur',
            field=models.ManyToManyField(blank=True, to='webapp.membre'),
        ),
    ]
