# Generated by Django 5.1.2 on 2024-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_projet_techno'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='techno',
            field=models.ManyToManyField(blank=True, to='webapp.techno'),
        ),
    ]
